<?php
use \Drupal\block_content\BlockContentInterface;
/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 * @param array $suggestions
 * @param array $variables
 */
function js_app_block_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // Block suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content']) && $variables['elements']['content']['#block_content'] instanceof BlockContentInterface) {
    array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
  }
}

function js_app_block_page_attachments(array &$attachments) {
  $react_global = \Drupal::config('js_app_block.settings')->get('global_react');
  // if our variable for setting react globally is set, include react
  // this still exists because users may or may not already have react loading in the site
  if ($react_global == 1){
    $attachments['#attached']['library'][] = 'js_app_block/react';
    $attachments['#attached']['library'][] = 'js_app_block/react-dom';
  }
  $enable_app = \Drupal::config('js_app_block.settings')->get('enable_js_app');
  // if our block is present, include the libraries needed
  // check to see if the js app is enabled through the admin page
  // if ($enable_app == 1){ 
  //   // in either case, include our library
  //   $attachments['#attached']['library'][] = 'js_app_block/js-app';
  // }
}

function js_app_block_block_build_alter(&$build, $block) {
  
  echo($build['elements']['content']['#block_content']->bundle());

}





/**
* Implements hook_preprocess_block() to modify the block variables
**/
//function js_app_block_preprocess_block(&$variables) {
 // foreach ($variables as $variable) echo($variable);
 // 
  //echo($variables['elements']['#block']);
  //if ($variables['block_type'] == 'javascript_app_block') {
   //echo($variables['block_type']);
  //   //$variables['classes'][] = "testclass";
  //   echo("found bundle");
  // }
  //echo($variables['entity_type']);
  // foreach ($variables['elements'] as $element) {
  //   echo($element . ' | ');
  // }
  // echo($variables['elements']);
  //$uuid = $variables['elements']['#block']['block_id'];
  // $block = \Drupal::service('entity.repository')->loadEntityByUuid('block_content', $uuid);
  // //if ($block) {
  //   $block_type = $block->bundle();
  //   echo($block_type);
  //}

//}

// /**
// * Implements hook_theme() to add the template definition.
// **/
// function js_app_block_theme($existing, $type, $theme, $path) {
//   return array(
//     'field__block_content__field_app_library__javascript_app_block' => array(),
//   );
// }


// register the templates
//function js_app_block_theme($existing, $type, $theme, $path) {
  // return [
  //   '' => [
  //     'variables' => ['test_var' => NULL],
  //   ],
  // ];
  // $theme['field__block_content__field_app_library__javascript_app_block'] = [
  //   'template' => 'field__block_content__field_app_library__javascript_app_block',
  // ];

  // return $theme;
  // return [
  //   'field__block_content__field_app_library__javascript_app_block' => [
  //     'template' => ['field__block_content__field_app_library__javascript_app_block'],
  //   ],
  // ];
//}

// function js_app_block_template_preprocess_block(array &$variables) {
//   //error?
//   $variables['attributes']['classes'][] = 'newclass';
// }