<?php
// logic getting info on any react blocks that may be present
// here

// include react library if necessary
function js_app_block_page_attachments(array &$attachments) {
  $react_global = \Drupal::config('js_app_block.settings')->get('global_react');
  // if our variable for setting react globally is set, or if a react block is present, include react
  if ($react_global == 1){
    $attachments['#attached']['library'][] = 'js_app_block/react';
    $attachments['#attached']['library'][] = 'js_app_block/react-dom';
  }
}