<?php
function react_sub_page_attachments(array &$attachments) {
  $react_global = \Drupal::config('react_sub.settings')->get('global_react');
  // if our variable for setting react globally is set, then enable it globally
  if ($react_global == 1){
    $attachments['#attached']['library'][] = 'react_sub/react';
    $attachments['#attached']['library'][] = 'react_sub/react-dom';
  // otherwise, parse through the different settings, turning it on and off based on the page we are on
  } else {

  }
}