js_app_block:
  type: mapping
  label: "Javascript App Block"
  mapping:
    global_react:
      type: boolean
      label: "React Installed Globally"
    app_script:
      type: string
      label: "Javascript App Block Script"