react_sub:
  type: mapping
  label: "React Subpages"
  mapping:
    global_react:
      type: boolean
      label: "React Installed Globally"
    app_script:
      type: string
      label: "React App Script"